;====================================================================
; Main.asm file generated by New Project wizard
/* =====================================
exemplo programa com interrupcao TC0 - timer 0 ,
comparacao de registradores A e B e PWM nos pinos 0C0A E 0C0B
MODO captura CTC (clock externo entrada pino PD4

*/
;====================================================================
; DEFINITIONS
;====================================================================
.equ vermelho = pb0
.equ amarelo = pb1
.equ verde = pb2
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================
.org 0x0000
      ; Reset Vector
      rjmp  Start
.org 0x001C
     rjmp TIM0_COMPA ; vetor comparacao tcnt0 com registrador OCR0A
.org 0x001E ; 
      rjmp trata_TIM0_COMPB ;  ; vetor comparacao tcnt0 com registrador OCR0B 

.org 0x050		
;====================================================================
; CODE SEGMENT
;====================================================================
.include "lib328Pv01.inc"
Start:
      ; Write your code here
	sbi ddrd,5
	sbi ddrd,6
	sbi ddrb,0
	sbi ddrb,1
	sbi ddrb,2

	ldi r16,0b01010010  ;  ativando pinos 0C0A E 0C0B com mudança na igualdade, operacao TC0 modo captura clock externo ctc
	out TCCR0A,r16
		/* TCCR0A  Registrador de controle A do TC0  
	COM0A1 COM0A0 COM0B1 COM0B0  -     -     WGM01 WGM00
	 7        6     5      4     3     2       1     0

	 COM0A1 COM0A0 controlam o comportamento do pino 0C0A pino D6 (modos normal, CTC, pwm rapido)
	   0      0  - pino 0C0A desconectado
	   0      1  - mudanca de estado na igualdade (modo normal)
	   1      0  - aterrado na igualdade(modo normal/pwm rapido) =0 crescente e =1 decrescente (pwm fase corrigida)
	   1      1  - Ativo  na igualdade (modo normal/pwm rapido) =1 crescente e =0 decrescente (pwm fase corrigida)

	   COM0B1 COM0B0  controlam o comportamento do pino 0C0B  pino D5
	   0      0  - pino 0C0B desconectado
	   0      1  - mudanca de estado na igualdade (modo normal)
	   1      0  - aterrado na igualdade (modo normal/pwm rapido) =0 crescente e =1 decrescente (pwm fase corrigida)
	   1      1  - Ativo  na igualdade (modo normal/pwm rapido) =1 crescente e =0 decrescente (pwm fase corrigida)

	   WGM02 WGM01 WGM00 bits do modo de controle, fonte do valor maximo e forma de onda
	   0     0     0  - normal     TOP em FF
	   0     0     1  - pwm fase corrigida top em FF
	   0     1     0  - CTC        TOP em 0CR0A
	   0     1     1  - pwm rapido  TOP em FF
	   1     0     0  - 
	   1     0     1  - pwm fase corrigida top em 0CR0A
	   1     1     0   -
	   1     1     1  - pwm rapido TOP em 0CR0A
	*/
	ldi r16,0b00000110  ;  habilitar interrupcao por overflow comparacao 0CR0A  0CR0B 
	sts TIMSK0,r16 
	/* TIMSK0 Interruptor de mascara do contador TC0
	- - - - - 0CIE0B 0CIE0A TOIE0
	7 6 5 4 3   2      1      0
	0CIE0B ativa a interrupção na igualdade de comparação 0CR0B
	0CIE0A ativa a interrupção na igualdade de comparação 0CR0A
	TOIE0  ativa a interrupção de estouro em TOP=FF

	*/

	ldi r16,0b00000110    ; clock externo borda descida
	out TCCR0B,r16   ; prescaler 1024
	/* TCCR0B  Registrador de controle B do TC0
	F0C0A  FOC0B   -    -   WGM02  CS02  CS01  CS00
	7        6     5    4     3      2    1      0

	CS02  CS01  CS00  bits de selecao do prescaler
	   0     0     0  - sem fonte de clock tc0 parado
	   0     0     1  - prescaler =1
	   0     1     0  - prescaler = 8
	   0     1     1  - prescaler = 64
	   1     0     0  - prescaler = 256
	   1     0     1  - prescaler = 1024
	   1     1     0  - clock externo pino T0 (pd4) contagem borda descida
	   1     1     1  - clock externo pino T0 (pd4) contagem borda subida     
	*/

    ldi r16,210
	out OCR0A,r16  ; alterando valores 0CR0A 
    ldi r16,105
	out OCR0B,r16  ; alterando valores 0CR0B  afeta apenas atraso de 0CR0B/0CR0A * periodo


    sei ; habilita as interrupções no microcontrolador


Loop:

    rjmp  Loop

;====================================================================
; rotina executada quando tcnt0 igual a OCR0A
TIM0_COMPA:
	sbic portb,0
	rjmp apagavermelho
	sbi portb,0
;	sbi	TIFR0, 1	
	reti
apagavermelho: ; pisca o amarelo
    cbi portb,0
	reti	
;==============================================================
; rotina executada quando tcnt0 igual a OCR0B
trata_TIM0_COMPB:
	sbic portb,1
	rjmp apagaamarelo
	sbi portb,1
	reti
apagaamarelo: ; pisca o amarelo
    cbi portb,1
	reti	
