;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   seg ago 24 2015
; Processor: ATmega328P
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================
.equ V1 = pb5	; Saída	(Atuador)	
.equ M1 = pb4	; Saída (Atuador)				
.equ S1 = pb0	; Entrada  (Sensor)
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================
.include "lib328Pv01.inc"
Start:
      ; Write your code here
      sbi ddrb,5	; Configura a porta pb5 como saída
      sbi ddrb,4	; Configura a porta pb4 como saída
      cbi ddrb,0	; Configura a porta pb0 como entrada
      sbi portb,0	; SET 1Habilita resistor de pull-up na porta pb0
Loop:
      cbi portb,V1 	;Fecha a válvula v1
      sbi portb,M1	; Aciona o motor M1
      

S1_OFF:
      sbic pinb,S1	; Pula a próxima instrução caso S1 esteja em 1 (Sensor desativado).Verifica se o pino PB0 está em 1 (setado)e pula a próxima instrução
      rjmp S1_OFF	; Volta para S1_OFF caso pino em (0) sensor ativado
      
S1_ON:
      sbis pinb,S1	 	; Pula a próxima instrução caso S1 esteja em 0 (Sensor ativado). Verifica se o pino pb0 está clear
      rjmp S1_ON	 	; Volta para S1_ON
      cbi portb,M1	 	; Desliga o motor M1
      sbi portb,V1	 	; Abre a vávula V1
      ldi delay_time,5  	; Carrega delay_time com 5 (5 segundos)
      rcall delay_seconds	; Chama rotina de atraso
      rjmp  Loop

;====================================================================
